server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/myapp?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true
    username: app_user
    password: app_password
  redis:
    database: 0
    port: 6379
    host: redis
    password: app_password

logging:
  level:
    com.hzx.lesson: info
  file:
    name: logs/app.log